# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 100000

runner: "parallel"
batch_size_run: 8
t_max: 10050000

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "maven_learner"
double_q: True
mixer: "maven_mix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

noise_dim: 2

entropy_scaling: 0.001

mi_loss: 1
noise_dim: 2
noise_embedding_dim: 32
noise_bandit: False

mi_intrinsic: False
mi_scaler: 0.1
hard_qs: False

bandit_epsilon: 0.1
bandit_iters: 8
bandit_batch: 64
bandit_buffer: 512
bandit_reward_scaling: 20
bandit_use_state: True
bandit_policy: True

rnn_discrim: False
rnn_agg_size: 32

discrim_size: 32
discrim_layers: 2

mac: "maven_mac"
agent: "maven"

name: "maven_env=8_adam"